### ISSUE TITLE
There was an error using thundergbm-predict file

### ISSUE THREAD

**Issue by lvpinrui** [Xtra-Computing/thundergbm#14] opened 2019-04-12 02:42 UTC
My environment is:
Windows 10
Visual Studio 2017 Community
CMake3.14.0-rc3
CUDA10.1.105
Using test_dataset.txt in the library is successful,but Using my own .txt is failed.
my  thundergbm-predict：
![image](https://user-images.githubusercontent.com/44189445/56008687-9d82d300-5d0f-11e9-93af-83a26dd975d5.png)

When building  thundergbm-predict ：
![image](https://user-images.githubusercontent.com/44189445/56008500-fdc54500-5d0e-11e9-8f3d-b496690281e8.png)

**Comment by jiahuanluo** [comment] 2019-04-13 06:53
Dear,
I have run several tests on similar [dataset](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass.html#usps), and no error occored.
Could you please provide more details or zip your dataset and put it here if available?
Make sure that your dataset is in a LibSVM format.
Thanks.

**Comment by lvpinrui** [comment] 2019-04-15 07:17
> Dear,
> I have run several tests on similar dataset [usps](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass/usps.bz2), and no error occurred.
> Could you please provide more details or zip your dataset and put it here if available?
> Make sure that your dataset is in a LibSVM format.
> Thanks.
hello,this is my dataset:

**Comment by lvpinrui** [comment] 2019-04-15 07:18
> 亲爱的，
> 我在类似的数据集[usps](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass/usps.bz2)上运行了几次测试，没有发生错误。
> 您能否提供更多详细信息或压缩您的数据集并将其放在此处（如果有）？
> 确保您的数据集采用LibSVM格式。
> 谢谢。
hello,this is my dataset:
[1.txt](https://github.com/Xtra-Computing/thundergbm/files/3078818/1.txt)

waiting for your advice,thanks!

**Comment by jiahuanluo** [comment] 2019-04-15 11:29
Hi there,
We found that your dataset is zero_based (the first index of feature is 0).
The newest version is able to handle zero_based dataset.
You can use the newest code or turn your dataset into one-based.
Thanks.

**Comment by lvpinrui** [comment] 2019-04-16 05:46
hello,Running the original code after changing my dataset succeeded.but i use the newest code,This has a new problem.
my thundergbm-train:
![image](https://user-images.githubusercontent.com/44189445/56184551-0db19180-604d-11e9-807c-17a2fbb2b07d.png)
my dataset is always 1.txt,
When building thundergbm-train ：
![image](https://user-images.githubusercontent.com/44189445/56184449-a0056580-604c-11e9-91ae-2baca1e261a3.png)



waiting for your advice,thank you very much.

**Comment by jiahuanluo** [comment] 2019-04-16 06:44
Hi lvpinrui,

Thanks for imforming.
You can delete the code in this [line](https://github.com/Xtra-Computing/thundergbm/blob/7215e107113c4004103a360d8f69539f08647536/src/thundergbm/CMakeLists.txt#L4) and rebuild the project.
There is a bug here, we will fix it in no time.

Regards

**Comment by lvpinrui** [comment] 2019-04-16 09:14
i use the newest code,When my dataset is 1.txt running  thundergbm-predict file  succeeds, but when the dataset is 2.txt  thundergbm-predict file fails ,this is a new problem
![image](https://user-images.githubusercontent.com/44189445/56194646-00ed6780-6066-11e9-881d-c655387b3ff9.png)
my dataset is 2.txt,2.txt file size is 1.43GB,I don't know if it is because the file is too big.

**Comment by jiahuanluo** [comment] 2019-04-16 09:28
It should work.
You should check your dataset, or share it through the cloud (Baidu Yun?)

**Comment by lvpinrui** [comment] 2019-04-16 09:36
this my dataset(Baidu Yun):
链接：https://pan.baidu.com/s/15H6YW_mqZP6K4hrOVl9eOA 
提取码：s9y7 

thank you very much!

**Comment by jiahuanluo** [comment] 2019-04-17 02:39
I have tested your dataset 2.txt on the newest code. No error has occurred.
@lvpinrui

**Comment by lvpinrui** [comment] 2019-04-17 03:13
> 我已在最新代码上测试了您的数据集2.txt。没有发生错误。
> @lvpinrui

hello ,thank you very much for your help.
but my Configuration is:
max_depth=6 num_round=40 n_gpus=1 verbosity=0 profiling=0 data=C:\Users\Administrator\Desktop\2\2.txt max_bin=255 colsample=1  bagging=1   num_parallel_tree=1 eta=1.0  objective=multi:softmax num_class=8 min_child_weight=1 lambda=1 gamma=1 tree_method=auto   
when building thundergbm-train is ok,
when building thundergbm-predict is failed.

**Comment by jiahuanluo** [comment] 2019-04-17 14:13
Yes, the same configuration as yours.
I ran the test via command line, editing the [machine.conf](https://github.com/Xtra-Computing/thundergbm/blob/master/dataset/machine.conf). It works fine for me.
@lvpinrui

**Comment by lvpinrui** [comment] 2019-04-18 05:52
> Yes, the same configuration as yours.
> I ran the test via command line, editing the [machine.conf](https://github.com/Xtra-Computing/thundergbm/blob/master/dataset/machine.conf). It works fine for me.
> @lvpinrui

thank you very much for your help these days.
I tried it a few times or not, I succeeded after changing my dataset.

**Comment by jiahuanluo** [comment] 2019-04-19 08:09
Since the issue is solved, I will close it.

Cheers,
Locke

**Closed by jiahuanluo** 2019-04-19 08:09 UTC
