### ISSUE TITLE
 use my own data in the thundergbm-predict file

### ISSUE THREAD

**Issue by lvpinrui** [Xtra-Computing/thundergbm#13] opened 2019-04-11 03:14 UTC
**My environment is:**
Windows 10
Visual Studio 2017 Community
CMake3.14.0-rc3
CUDA10.1.105
Using test_dataset.txt in the library is successful,but Using my own .txt is failed.
**### my config file is:**
max_depth=6
num_round=40
n_gpus=1
verbosity=0
profiling=0
data=D:\thundergbm\dataset\2.txt
max_bin=255
colsample=1
bagging=1
num_parallel_tree=1
eta=1.0
objective=multi:softmax
num_class=8
min_child_weight=1
lambda=1
gamma=1
model_out=tgbm.model
model_in=D:\thundergbm\build\tgbm.model
tree_method=auto
Errors output:
CUDA error 2 [D:\thundergbm\src\thundergbm\syncmem.cpp, 238]: out of memory
waiting for your advice,thank you~!

**Comment by jiahuanluo** [comment] 2019-04-13 06:44
Duplicate of https://github.com/Xtra-Computing/thundergbm/issues/14#

**Closed** 2019-04-13 06:44 UTC
