### ISSUE TITLE
issue with saving and reloading model?

### ISSUE THREAD

**Issue by AlanSpencer2** [Xtra-Computing/thundergbm#75] opened 2022-01-26 17:21 UTC
I am trying to save a trained model using: clf.save_model(path)... But when I reload the model, it doesn´t produce the same results as the saved model, despite using the same exact test data. 

I reloaded with the command clf.load_model(path).

What is the cause of this problem? How can I save and reload models successfully?

**Comment by Kurt-Liuhf** [comment] 2022-02-10 01:41
Hi @AlanSpencer2, I tried to reproduce your issue on dataset ` covtype `which is a dataset for classification. And I used the same methods as you mentioned, `clf.save_model(path)` and` clf.load_model(path)`, but the prediction results are exactly the same before and after model saving and reloading. Please provide more information (e.g., dataset you used, type of task, model parameters, etc.) to help us reproduce the issue.

**Comment by zeyiwen** [comment] 2022-09-18 13:58
@AlanSpencer2 I'm closing this issue, as the codebase works fine in the case and we are unable to reproduce the issue reported.

**Closed by zeyiwen** 2022-09-18 13:58 UTC
